name = "gifgrep"
version = "1.0.0"
description = "Search and browse GIF databases via Giphy or Tenor APIs"
author = "Aegis Team"
category = "search"
permissions = []
entry_point = "run.sh"
dependencies = []
min_aegis_version = "0.1.0"
required_bins = []
required_env = []
os = []

