name = "things-mac"
version = "1.0.0"
description = "Create and manage tasks in Things 3 via AppleScript and URL schemes"
author = "Aegis Team"
category = "productivity"
permissions = []
entry_point = "run.sh"
dependencies = []
min_aegis_version = "0.1.0"
required_bins = []
required_env = []
os = ["darwin"]

[[commands]]
name = "things"
description = "Create or list tasks in Things 3"
usage = "/things [add|today|inbox|search] [text]"
aliases = ["todo"]
